title: 我的世界
subtitle: 欢迎你来到我的世界
description: >- # this means to ignore newlines until "baseurl:"
  欢迎你来到我的世界

url: "https://www.open6.cn" # the base hostname & protocol for your site, e.g. https://example.github.io
baseurl: "" # the subpath of your site, e.g. /blog

urls:
    - text: 博客
      url: /blog
    - text: 商城
      url : /shop/
    - text: 关于我
      url: /about/
    - text: 联系我
      url : /contact/
    - text: 格式指南
      url: /styleguide/
    

# Edit these details 

author_logo: profile.png
author: watrt(似水无痕)
author_bio: 嗨!我是watrt，我喜欢编程，还有玩弄各种电子设备，欢迎你一起来交流。
author_email: "xb100@qq.com"
author_location: 中国
author_website_url: "https://open6.cn"

author_work_experiences: 
            - company_name: Google
              company_logo: google.png
              company_url: https://google.com
              designation: Software Engineer
              description: Worked on various Google Products
              visibility: true
            - company_name: Microsoft
              company_logo: microsoft.png
              company_url: https://microsoft.com
              designation: Azure Developer
              description: Worked on various Azure Cloud Products
              visibility: true

author_education_details:
              - college_logo: mit.png
                college_name: MIT
                college_url: wpython
                college_degree: CS Engineer
                description: Bachelor of Technology
                visibility: true

author_project_details:
              - project_thumbnail: p2.png
                project_title: EsPy_cn
                project_description: 这个是一个micppython开以IDE改进项目。
                project_url: https://github.com/watrt/EsPy_cn
                visibility: true
              - project_thumbnail: p1.png
                project_title: wpython
                project_description: 这是一个基于esp32硬件下使用micropython进行开发的项目
                project_url: https://github.com/watrt/wpython
                visibility: true

# social links
twitter_username: watrt
github_username:  watrt
facebook_username: watrt
linkedin_username: watrt
behance_username: watrt
instagram_username: watrt
medium_username: watrt
telegram_username: watrt
dribbble_username: watrt
flickr_username: watrt

#for comments using disqus
disqus_shortname: watrt  

# wakatime username (coding activity)
wakatime_username: watrt

# formspree (contact form)
formspree_email: watrt@qq.com

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
google_analytics: UA-46783401-10 

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: true

# dont touch this unless required
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-algolia
# - jekyll-archives

# algolia search 
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 8
per_page: 4
paginate_path: "/blog/page/:num/"

# minify 
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'


collections:
 - products

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
